- set_fact: date_stamp="{{ lookup('pipe','date +%Y%m%d%H%M') }}"
  tags: vars
- set_fact: day_stamp="{{ lookup('pipe','date +%Y%m%d') }}"
  tags: vars

- name: Ensures backup_dir exists
  file:
    path: '{{ backup_dir }}'
    state: directory
    mode: '{{ backup_dir_mode }}'
    owner: '{{ backup_dir_owner }}'
    group: '{{ backup_dir_group }}'

- name: Run backup pre commands
  command: "{{ item }}"
  with_items: '{{ backup_pre_commands | default([]) }}'

- include_tasks: clear.yml
  tags: clear

- include_tasks: db_mysql.yml
  tags: mysql
  when: backup_with_mysql

- include_tasks: db_postgresql.yml
  tags: postgresql
  when: backup_with_postgresql

- include_tasks: files.yml
  tags: files
  with_items: "{{ backup_sets | default([]) }}"
  loop_control:
    loop_var: instance

- include_tasks: rsync.yml
  tags: sync
  when: backup_remote_host != '' and backup_remote_transfer == 'rsync'

- include_tasks: lftp.yml
  tags: sync
  when: backup_remote_host != '' and backup_remote_transfer == 'lftp'

- name: Run backup post commands
  command: "{{ item }}"
  with_items: '{{ backup_post_commands | default([]) }}'
