- name: Check required variables for borg
  fail:
    msg: 'backup_borg_sets, backup_borg_repo and backup_borg_passphrase has to be specified for borg'
  when: >
    backup_borg_sets == ''
    or backup_borg_repo == ''
    or backup_borg_passphrase == ''

- name: Be sure borg is installed
  apt:
    name: borgbackup
    state: present

- name: Get repository information
  command: borg info -v {{ backup_borg_repo }}
  ignore_errors: yes
  register: borg_info
  environment:
    BORG_PASSPHRASE: '{{ backup_borg_passphrase }}'

- name: Init borg repository
  command: borg init --encryption={{ backup_borg_encryption_mode }} {{ backup_borg_repo }}
  ignore_errors: yes
  register: borg_init
  environment:
    BORG_PASSPHRASE: '{{ backup_borg_passphrase }}'
  when: borg_info.rc != 0

- name: Create borg backup
  command: >
    borg create --compression {{ backup_borg_compression }} --stats
    {{ backup_borg_repo }}::{hostname}-{now:%Y-%m-%d_%H:%M}
    {% for borg_set in backup_borg_sets %}{{ borg_set.src }} {% endfor %}
  register: borg_create
  environment:
    BORG_PASSPHRASE: '{{ backup_borg_passphrase }}'

- name: Run repository tasks
  block:
    - name: Show borg create info
      debug: var=borg_create.stdout_lines

    - name: Run borg prune
      command: >
        borg prune -v --list
        --keep-daily={{ backup_borg_prune_keep_daily }}
        --keep-weekly={{ backup_borg_prune_keep_weekly }}
        --keep-monthly={{ backup_borg_prune_keep_monthly }}
        --keep-yearly={{ backup_borg_prune_keep_yearly }}
        {{ backup_borg_repo }}
      environment:
        BORG_PASSPHRASE: '{{ backup_borg_passphrase }}'
      when: backup_borg_with_prune

    - name: Run borg check (if activated)
      command: >
        borg check -v
        {{ backup_borg_repo }}
      environment:
        BORG_PASSPHRASE: '{{ backup_borg_passphrase }}'
      when: backup_borg_with_check

    - name: With repository information (if activated)
      block:
        - name: Get latest repository information
          command: borg info -v {{ backup_borg_repo }}
          register: info
          environment:
            BORG_PASSPHRASE: '{{ backup_borg_passphrase }}'

        - name: Show borg info
          debug: var=info.stdout_lines

      when: backup_borg_with_info

  when: borg_create.rc == 0
