- name: Check required variables for borg
  fail:
    msg: 'backup_borg_repo and backup_borg_passphrase or backup_borg_repo2 and backup_borg_passphrase2 has to be set'
  when: >
    backup_borg_repo == '' and backup_borg_passphrase
    or backup_borg_repo2 == '' and backup_borg_passphrase2

- name: Include borg binary tasks
  include_tasks: borg_from_binary.yml

- name: Include borg package tasks
  include_tasks: borg_from_package.yml

- name: Set facts borg_binary
  set_fact:
    borg_binary: "{{ backup_borg_binary if backup_borg_install_from_binary else '/usr/bin/borg' }}"

- name: Run REPO1 tasks
  block:
    - name: Set facts borg_repo for REPO1
      set_fact:
        borg_repo_name: 'REPO1'
        borg_repo: "{{ backup_borg_repo }}"
        borg_passphrase: "{{ backup_borg_passphrase }}"

    - name: Include Repo tasks for REPO1
      include_tasks: borg_repo.yml

  when: backup_borg_repo != ''

- name: Run REPO2 tasks
  block:
    - name: Set facts borg_repo for REPO2
      set_fact:
        borg_repo_name: 'REPO2'
        borg_repo: "{{ backup_borg_repo2 }}"
        borg_passphrase: "{{ backup_borg_passphrase2 }}"

    - name: Include Repo tasks for REPO2
      include_tasks: borg_repo.yml

  when: backup_borg_repo2 != ''
