---
# sync wih sync_master
# files from master are synced to client
# sync files from sync_master -> hostname (inventory_hostname)
# sync_master has to be the ip address!!!

# delegate_to is not working
#- name: sync client {{ inventory_hostname }} with sync_master {{ sync_master }}
#  synchronize:
#    mode: push
#    src: '{{ item }}/'
#    dest: '{{ item }}'
#    delete: yes
#    archive: yes
#    rsync_timeout: 10
#    verify_host: no
#  with_items: '{{ backup_sync_files }}'
#  delegate_to: '{{ sync_master }}'

- name: Sync database client {{ inventory_hostname }} with sync_master {{ sync_master }}
  tags: db
  command: '{{ backup_drush_path }} --yes sql-sync @sync_master_{{ item.profile }} @sync_client_{{ item.profile }}'
  with_items: '{{ backup_sync | default([]) }}'
  when: item.db_url is defined

- name: Sync files client {{ inventory_hostname }} with sync_master {{ sync_master }}
  tags: files
  command: '{{ backup_drush_path }} --yes rsync @sync_master_{{ item.profile }}:%files/ @sync_client_{{ item.profile }}:%files --delete'
  with_items: '{{ backup_sync | default([]) }}'
  when: item.files is defined
