---

- name: Get MySQL databases
  command: "mysql -Bse 'show databases'"
  register: db_list
  changed_when: db_list.rc != 0

- name: Create MySQL dumps
  mysql_db:
    name: '{{ item }}'
    target: "{{ backup_dir }}/db-{{ item }}-{{ date_stamp }}{{ backup_db_dump_format }}"
    state: dump
    single_transaction: '{{ backup_mysql_single_transaction }}'
  with_items: "{{ db_list.stdout_lines | default([]) }}"
  when: db_list.stdout_lines | length and item not in backup_mysql_db_excludes

- name: Create hash file of MySQL backups
  shell: "sha256sum db-{{ item }}-{{ date_stamp }}{{ backup_db_dump_format }} > db-{{ item }}-{{ date_stamp }}{{ backup_db_dump_format }}.sha256"
  args:
    chdir: "{{ backup_dir }}"
  with_items: "{{ db_list.stdout_lines | default([]) }}"
  when: backup_create_hashfiles and db_list.stdout_lines | length and item not in backup_mysql_db_excludes
