- set_fact: excludes="{{ instance.excludes | default([]) }}"

- name: Create backup of files/directories - {{ instance.name }}
  command: "tar --exclude={{ excludes | join(' --exclude=') }} -cplzf {{ backup_dir }}/{{ instance.name }}-{{ date_stamp }}.tar.gz {{ instance.src | basename }}"
  args:
    chdir: "{{ instance.src | dirname }}"

- name: Create hash file of backup sets - {{ instance.name }}
  shell: "sha256sum {{ instance.name }}-{{ date_stamp }}.tar.gz > {{ backup_dir }}/{{ instance.name }}-{{ date_stamp }}.tar.gz.sha256"
  args:
    chdir: "{{ backup_dir }}"
  when: backup_create_hashfiles
