---
- name: Set facts
  ansible.builtin.set_fact:
    excludes: "{{ instance.excludes | default([]) }}"
    unsafe_writes: "{{ instance.unsafe_writes | default(backup_files_unsafe_writes) }}"
    backup_file_name: "{{ instance.name }}-{{ date_stamp }}-{{ backup_file_period }}.tar.gz"

# see https://docs.ansible.com/ansible/latest/collections/community/general/archive_module.html
# TODO: archive only creates files with absolute path
- name: Create backup of files/directories - {{ instance.name }}
  community.general.archive:
    path: '{{ instance.src }}'
    dest: '{{ backup_dir }}/{{ backup_file_name }}'
    format: gz
    mode: 0644
    exclude_path: '{{ excludes }}'
    unsafe_writes: '{{ unsafe_writes | default(omit) }}'
  become: "{{ backup_files_become | default(omit) }}"
  become_user: '{{ backup_files_become_user | default(omit) }}'

- name: Include checksum file
  ansible.builtin.include_tasks: checksum_file.yml
  vars:
    orig_file: '{{ backup_dir }}/{{ backup_file_name }}'
    owner: "{{ backup_files_become_user | default('root') }}"
  when: backup_create_hashfiles
