---
- name: Set backup file name - mongodb databases
  ansible.builtin.set_fact:
    backup_file_name: "db-{{ date_stamp }}-{{ backup_file_period }}.mongo_archive"

# @see https://docs.mongodb.com/manual/reference/program/mongodump/
- name: Create mongodb dump
  ansible.builtin.shell: "mongodump {{ backup_mongodb_options }} > {{ backup_dir }}/{{ backup_file_name }}"

- name: Include checksum file
  ansible.builtin.include_tasks: checksum_file.yml
  vars:
    orig_file: '{{ backup_dir }}/{{ backup_file_name }}'
    owner: root
  when: backup_create_hashfiles
