---
- name: Get postgresql databases
  community.postgresql.postgresql_query:
    db: postgres
    query: SELECT datname AS database FROM pg_database WHERE NOT datistemplate AND datname <> 'postgres'
  register: db_list
  become_user: postgres
  become: true

- name: Include PostgreSQL db tasks
  ansible.builtin.include_tasks: postgresql_db.yml
  loop: "{{ db_list.query_result | default([]) }}"
  loop_control:
    loop_var: db
