---
- name: Set backup file name - {{ db.database }}
  ansible.builtin.set_fact:
    backup_file_name: "db-{{ db.database }}-{{ date_stamp }}-{{ backup_file_period }}.pg_dump"

- name: Create postgresql dump - {{ db.database }}
  community.postgresql.postgresql_db:
    name: '{{ db.database }}'
    target: '{{ backup_dir }}/{{ backup_file_name }}'
    dump_extra_args: '{{ backup_postgresqldump_options }}'
    state: dump
  become_user: postgres
  become: true

- name: Include checksum file
  ansible.builtin.include_tasks: checksum_file.yml
  vars:
    orig_file: '{{ backup_dir }}/{{ backup_file_name }}'
    owner: postgres
  when: backup_create_hashfiles
