---
- name: Set backup file name - {{ db }}
  set_fact: backup_file_name="db-{{ db }}-{{ date_stamp }}-{{ backup_file_period }}.pg_dump"

- name: Create postgresql dump - {{ db }}
  shell: "pg_dump {{ backup_postgresqldump_options }} {{ db }} > {{ backup_dir }}/{{ backup_file_name }}"
  become_user: postgres
  become: true

- name: Create hash file for dump - {{ db }}
  shell: "sha256sum {{ backup_file_name }} > {{ backup_file_name }}.sha256"
  args:
    chdir: "{{ backup_dir }}"
  when: backup_create_hashfiles
